#!/usr/bin/env python3
"""
DEVKiTZ VPS Auto-Update Pipeline
================================
Laeuft als Cron auf dem VPS (alle 4 Stunden).
Aktualisiert: llms.txt, features.json, README Sync, Deploy.

Cron Setup:
  0 */4 * * * /usr/bin/python3 /opt/devkitz/scripts/vps-auto-update.py >> /var/log/devkitz-update.log 2>&1

Oder als systemd Timer:
  [Timer]
  OnCalendar=*-*-* 0/4:00:00
  Persistent=true
"""

import json
import os
import subprocess
import sys
import hashlib
import base64
from datetime import datetime
from pathlib import Path

# === KONFIGURATION ===

REPO_DIR = "/opt/devkitz/workspace"  # Git Repo auf VPS
DEPLOY_DIR = "/var/www/devkitz"      # nginx root
GITHUB_ORG = "D-VKITZ"
GITHUB_REPO = "7IKED/devkitz-workspace"
LOG_FILE = "/var/log/devkitz-update.log"

DASHBOARD_DIR = os.path.join(REPO_DIR, "01_PROJECTS/01_dashboard")
MODULES_DIR = os.path.join(DASHBOARD_DIR, "modules")
SKILLS_DIR = os.path.join(REPO_DIR, ".agents/skills")
WORKFLOWS_DIR = os.path.join(REPO_DIR, ".agents/workflows")


def log(msg):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] {msg}"
    print(line)


def run(cmd, cwd=None):
    """Shell-Befehl ausfuehren"""
    result = subprocess.run(
        cmd, shell=True, cwd=cwd,
        capture_output=True, text=True, timeout=120
    )
    if result.returncode != 0:
        log(f"  [WARN] Command failed: {cmd}")
        log(f"  STDERR: {result.stderr[:200]}")
    return result.stdout.strip(), result.returncode


# === PHASE 1: Git Pull ===

def git_pull():
    log("[1/6] Git Pull...")
    out, rc = run("git pull origin main --no-edit", cwd=REPO_DIR)
    if rc == 0:
        log(f"  OK: {out[:100]}")
    return rc == 0


# === PHASE 2: features.json generieren ===

def update_features():
    log("[2/6] Updating features.json...")
    if not os.path.isdir(MODULES_DIR):
        log("  [SKIP] Modules dir not found")
        return

    modules = []
    for entry in sorted(os.listdir(MODULES_DIR)):
        mod_path = os.path.join(MODULES_DIR, entry)
        if not os.path.isdir(mod_path):
            continue

        index_html = os.path.join(mod_path, "index.html")
        has_index = os.path.isfile(index_html)

        mod_info = {
            "name": entry,
            "path": f"modules/{entry}/",
            "has_index": has_index,
            "status": "active" if has_index else "empty",
            "size_bytes": os.path.getsize(index_html) if has_index else 0,
            "version": "v1.00.0_01"
        }

        if has_index:
            mod_info["last_modified"] = datetime.fromtimestamp(
                os.stat(index_html).st_mtime
            ).isoformat()

        modules.append(mod_info)

    features = {
        "generated": datetime.now().isoformat(),
        "generator": "vps-auto-update v1.0",
        "stats": {
            "total_modules": len(modules),
            "active_modules": sum(1 for m in modules if m["status"] == "active"),
            "empty_modules": sum(1 for m in modules if m["status"] == "empty"),
        },
        "modules": modules
    }

    features_path = os.path.join(DASHBOARD_DIR, "features.json")
    with open(features_path, "w", encoding="utf-8") as f:
        json.dump(features, f, indent=2, ensure_ascii=False)

    log(f"  OK: {features['stats']['total_modules']} modules")


# === PHASE 3: llms.txt aktualisieren ===

def update_llms_txt():
    log("[3/6] Updating llms.txt files...")

    # Root llms.txt
    root_llms = os.path.join(REPO_DIR, "llms.txt")
    if os.path.isfile(root_llms):
        # Modul-Count aktualisieren
        module_count = len([
            d for d in os.listdir(MODULES_DIR)
            if os.path.isdir(os.path.join(MODULES_DIR, d))
        ]) if os.path.isdir(MODULES_DIR) else 0

        with open(root_llms, "r", encoding="utf-8") as f:
            content = f.read()

        # Zeile mit "130+" oder aehnlich ersetzen
        import re
        content = re.sub(
            r"(\d+)\+? Dashboard-Modulen",
            f"{module_count}+ Dashboard-Modulen",
            content
        )
        content = re.sub(
            r"Dashboard \(\d+\+ Module\)",
            f"Dashboard ({module_count}+ Module)",
            content
        )

        with open(root_llms, "w", encoding="utf-8") as f:
            f.write(content)

        log(f"  OK: Root llms.txt updated ({module_count} modules)")

    # Module llms.txt
    modules_llms = os.path.join(MODULES_DIR, "llms.txt")
    if os.path.isdir(MODULES_DIR):
        lines = [
            "# Dashboard Module - llms.txt\n\n",
            f"> {datetime.now().strftime('%Y-%m-%d')} â€” Auto-generated by VPS Pipeline\n",
            f"> Entry-Point: llms.txt (Root)\n\n",
            "## Module\n\n",
            "| Modul | Status | Pfad |\n",
            "|:------|:-------|:-----|\n",
        ]
        for entry in sorted(os.listdir(MODULES_DIR)):
            if entry == "llms.txt":
                continue
            mod_path = os.path.join(MODULES_DIR, entry)
            if not os.path.isdir(mod_path):
                continue
            has_index = os.path.isfile(os.path.join(mod_path, "index.html"))
            status = "Active" if has_index else "Empty"
            lines.append(f"| {entry} | {status} | modules/{entry}/ |\n")

        with open(modules_llms, "w", encoding="utf-8") as f:
            f.writelines(lines)

        log(f"  OK: Module llms.txt generated")


# === PHASE 4: Skills + Workflows llms.txt ===

def update_skills_llms():
    log("[4/6] Updating skills + workflows llms.txt...")

    for label, dir_path in [("Skills", SKILLS_DIR), ("Workflows", WORKFLOWS_DIR)]:
        if not os.path.isdir(dir_path):
            log(f"  [SKIP] {label} dir not found")
            continue

        llms_path = os.path.join(dir_path, "llms.txt")
        entries = sorted(os.listdir(dir_path))

        lines = [
            f"# {label} - llms.txt\n\n",
            f"> Auto-generated {datetime.now().strftime('%Y-%m-%d')}\n\n",
            f"| Name | Typ |\n",
            f"|:-----|:----|\n",
        ]

        for entry in entries:
            if entry in ("llms.txt", ".DS_Store", "__pycache__"):
                continue
            full = os.path.join(dir_path, entry)
            if os.path.isdir(full):
                # Skill with SKILL.md
                skill_md = os.path.join(full, "SKILL.md")
                if os.path.isfile(skill_md):
                    lines.append(f"| {entry} | Skill (SKILL.md) |\n")
                else:
                    lines.append(f"| {entry} | Directory |\n")
            elif entry.endswith(".md"):
                lines.append(f"| {entry} | Workflow |\n")

        with open(llms_path, "w", encoding="utf-8") as f:
            f.writelines(lines)

        log(f"  OK: {label} llms.txt ({len(entries)} entries)")


# === PHASE 5: Deploy zu nginx ===

def deploy():
    log("[5/6] Deploying to nginx...")
    if not os.path.isdir(DEPLOY_DIR):
        os.makedirs(DEPLOY_DIR, exist_ok=True)

    src = os.path.join(DASHBOARD_DIR, "")
    out, rc = run(
        f"rsync -av --delete --exclude='.git' --exclude='node_modules' "
        f"{src} {DEPLOY_DIR}/",
        cwd=REPO_DIR
    )

    if rc == 0:
        log(f"  OK: Deployed to {DEPLOY_DIR}")
        run("sudo nginx -t && sudo systemctl reload nginx")
    else:
        log(f"  [WARN] Deploy failed")


# === PHASE 6: Git Commit + Push ===

def git_commit():
    log("[6/6] Git commit + push...")
    out, rc = run("git status --porcelain", cwd=REPO_DIR)
    if not out:
        log("  [SKIP] No changes")
        return

    run("git add -A", cwd=REPO_DIR)
    run(
        f'git commit -m "chore(vps): Auto-update {datetime.now().strftime("%Y-%m-%d %H:%M")}"',
        cwd=REPO_DIR
    )
    run("git push origin main", cwd=REPO_DIR)
    log("  OK: Pushed to origin")


# === MAIN ===

def main():
    log("=" * 60)
    log("  DEVKiTZ VPS Auto-Update Pipeline v1.0")
    log("=" * 60)

    success = True

    try:
        if not git_pull():
            log("[WARN] Git pull failed, continuing with local...")

        update_features()
        update_llms_txt()
        update_skills_llms()
        deploy()
        git_commit()

    except Exception as e:
        log(f"[ERROR] Pipeline failed: {e}")
        success = False

    log("=" * 60)
    log(f"  STATUS: {'OK' if success else 'FAILED'}")
    log(f"  TIME:   {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    log("=" * 60)

    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
